name = "WignerFunctions"
uuid = "254dfee8-34ea-5651-b6ea-a82e9a16dad9"
keywords = ["mathematics", "special function"]
license = "MIT"
desc = "Just some stuff to generate Wigner functions"
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
